Задачи 4.3, 5.1, 5.2
js-tasks-ru/jsbasic-20230911_oleg-vasilev pull request #4
Opened 2023-10-01 16:05 UTC by Onlaino

2023-10-01 16:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-02 14:38 UTC, SinimaWath reviewed
Тут все ок, давай решим все добавленные задачи

2023-10-02 14:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-02 14:48 UTC, Onlaino commented
Error: Process completed with exit code 1.
Что значит эта ошибка, Висит с задачи 4.3.

2023-10-04 21:06 UTC, SinimaWath requested changes

2023-10-04 21:06 UTC, SinimaWath commented on 4-module/3-task/index.js
> +const table = document.querySelector(".js-teachers");
В задаче, надо использовать только аргумент функции table. Давай уберем эту строчку

2023-10-04 21:06 UTC, SinimaWath commented on 4-module/3-task/index.js
> +highlight(table)
давай уберем вызов функции здесь

2023-10-04 21:06 UTC, SinimaWath commented on 5-module/1-task/index.js
> +hideSelf()
давай уберем вызов функции

2023-10-05 13:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-10-07 14:57 UTC, SinimaWath approved these changes

2023-10-07 14:57 UTC, merged